---
- hosts: app_nodes
  become: yes
  vars:
    app_url: https://github.com/jkanclerz/computer-programming-4/releases/download/v1.29/my-ecommerce-0.1.jar
    app_dir: /opt/ecommerce
    app_name: ecommerce
    my_favourite_software:
      - cowsay
      - mc
      - tree
    must_have_software:
      - java-17-amazon-corretto
  tasks:
    - name: "My first comment via ansible"
      command: "echo 'hello world' > hello_world.txt"
    - name: "install my favourite software"
      dnf:
        name: "{{ my_favourite_software }}"
        state: latest
    - name: "install must have software"
      dnf:
        name: "{{ must_have_software }}"
        state: latest
    - name: "create my file directory"
      file:
        path: "{{app_dir}}"
        state: directory
    - name: "download my app"
      get_url:
        url: "{{ app_url }}"
        dest: "{{ app_dir }}/{{ app_name }}.jar"
    - name: "Put my service config to systemd destiation"
      template:
        src: templates/app.service.j2
        dest: "/etc/systemd/system/{{ app_name }}.service"
    - name: "Start & add autostart my app"
      systemd_service:
        name: "{{ app_name }}"
        state: restarted
        enabled: yes
        daemon-reload: yes

- hosts: db_nodes
  become: yes
  vars:
    my_favourite_software:
      - cowsay
    must_have_soft:
      - MariaDB-server
      - MariaDB-client
  tasks:
    - name: "Put my repo config to Mariadb repo"
      template:
        src: templates/mariadb.repo.j2
        dest: "/etc/yum.repos.d/Mariadb.repo"
    - name: Install MariaDB Server and Client
      dnf:
        name: "{{ must_have_soft }}"
        state: latest
    - name: Start and enable MariaDB service
      systemd:
        name: mariadb
        state: started
        enabled: yes
    - name: "install my favourite software"
      dnf:
        name: "{{ my_favourite_software }}"
        state: latest

- hosts: lb_nodes
  become: yes
  vars:
    app_node_ips:
      - 172.31.30.117
  tasks:
    - name: install nginx
      dnf:
        name: nginx
        state: latest
    - name: copy conf
      template:
        src: templates/nginx.conf
        dest: /etc/nginx/conf.d/ecpmmerce.conf
    - name: start my nginx
      systemd_service:
        name: nginx
        state: restarted
